services:  
  chrony:
    container_name: chrony
    image: cturra/ntp
    restart: always
    networks:
      - localnet
    environment:
      - NTP_SERVERS=time.windows.com
    ports:
      - 123:123