restart: unless-stopped
hostname: rabbitmq
dns:
  subdomain: rabbitmq

# only used if traefik is disabled
ports:
  default: 5672
  ui: 15672

traefik: true
watchtower: true

networks:
  default:
    assignIp: true
    suffix: "0.55"
