# https://gitlab.com/NickBusey/HomelabOS/-/blob/dev/roles/gitlab/templates/docker-compose.gitlab.yml.j2?ref_type=heads
services:
  registry:
    image: registry:{{ gitlab.registry_version }}
    hostname: 'registry'
    restart: unless-stopped
    environment:
      - REGISTRY_HTTP_SECRET={{ lookup('password', './settings/passwords/gitlab_registry_secret chars=ascii_letters') }}
      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_AUTH_TOKEN_REALM=https://gitlab.{{ domain }}/jwt/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
      - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.crt
{% if gitlab.aws_registry_enabled %}
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_REGION={{ aws.region }}
      - REGISTRY_STORAGE_S3_ACCESSKEY={{ aws.access_key }}
      - REGISTRY_STORAGE_S3_SECRETKEY={{ aws.secret_key }}
      - REGISTRY_STORAGE_S3_BUCKET={{ gitlab.aws_registry_bucket }}
{% else %}
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
{% endif %}
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelabos_traefik"
      - "traefik.http.services.registry.loadbalancer.server.scheme=http"
      - "traefik.http.services.registry.loadbalancer.server.port=80"
      - "traefik.http.routers.registry-http.rule=Host(`{% if gitlab.registry.domain %}{{ gitlab.registry.domain }}{% else %}{{ gitlab.registry.subdomain + "." + domain }}{% endif %}`)"
      - "traefik.http.routers.registry-http.entrypoints=http"
{% if not gitlab.registry.https_only %}
      - "traefik.http.routers.registry-http.middlewares={% if gitlab.registry.https_only %}redirect@file, {% else %}{% if gitlab.registry.auth %}{% if authelia.enable %}authelia@file{% else %}basicAuth@file{% endif %}, {% endif %}{% endif %}customFrameHomelab@file"
{% else %}
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.registry-http.middlewares=redirect-to-https"
{% endif %}
      - "traefik.http.routers.registry.rule=Host(`{% if gitlab.registry.domain %}{{ gitlab.registry.domain }}{% else %}{{ gitlab.registry.subdomain + "." + domain }}{% endif %}`)"
      - "traefik.http.routers.registry.entrypoints=https"
      - "traefik.http.routers.registry.middlewares={% if gitlab.registry.auth %}{% if authelia.enable %}authelia@file{% else %}basicAuth@file{% endif %}, {% endif %}customFrameHomelab@file"
      - "traefik.http.routers.registry.tls=true"
{% if traefik.dns_challenge_provider %}
      - "traefik.http.routers.registry.tls.certresolver=dns"
      - "traefik.http.routers.registry.tls.domains[0].main={{ domain }}"
      - "traefik.http.routers.registry.tls.domains[0].sans=*.{{ domain }}"
{% else %}
      - "traefik.http.routers.registry.tls.certresolver=http"
{% endif %}
{% if enable_tor %}
      - "traefik.http.routers.registry-tor-http.rule=Host(`{{ lookup('vars', service_item).subdomain }}.{{ tor_domain }}`)"
      - "traefik.http.routers.registry-tor-http.entrypoints=http"
      - "traefik.http.routers.registry-tor-http.middlewares={% if gitlab.registry.auth %}{% if authelia.enable %}authelia-tor@file{% else %}basicAuth@file{% endif %}, {% endif %}customFrameHomelab-tor@file"
{% endif %}
    volumes:
      - "{{ volumes_root }}/gitlab/certs:/certs"
      - "{{ volumes_root }}/gitlab/registry:/var/lib/registry"
    expose:
      - "5000"
    ports:
      - '5000:5000'
    networks:
      - gitlab
    depends_on:
      - gitlab-runner
