restart: unless-stopped
hostname: mssql

pgid: 1000
puid: 1000
user: root

ports:
  default: 1433

dns:
  subdomain: mssql

mssql:
  pid: "Developer"

healthcheck:
  timeout: 45s
  interval: 10s
  retries: 10
  startPeriod: 90s

traefik: false
watchtower: true

networks:
  default:
    assignIp: true
    suffix: "0.31"