restart: unless-stopped
hostname: vault
command: vaule server -config=/config/config.json
dns:
  subdomain: vault

vault:
  client:
    sleep: 15
  addr: http://127.0.0.1:8200
  api:
    addr: http://127.0.0.1:8200
  config: |
    {
      "ui": true,
      "listener": [
          {
              "tcp": {
                  "address": "0.0.0.0:8200",
                  "tls_disable": 1
              }
          }
      ],
      "storage": {
          "file": {
              "path": "/vault/file"
          }
      },
      "max_lease_ttl": "10h",
      "default_lease_ttl": "10h"
    }

ports:
  default: 8200

traefik: true
watchtower: true

networks:
  default:
    assignIp: true
    suffix: "0.54"
