https://gitlab.com/NickBusey/HomelabOS/-/blob/dev/roles/gitlab/templates/docker-compose.gitlab.yml.j2?ref_type=heads
  gitlab-runner:
    image: gitlab/gitlab-runner:{{ gitlab.runner_version }}
    command: register -n --locked=false --url "http://gitlab/" --registration-token "{{ lookup('password', './settings/passwords/gitlab_runners_token chars=ascii_letters') }}" --clone-url http://gitlab --executor "docker" --docker-image "docker:latest" --docker-privileged --description "docker-runner" --tag-list "docker" --run-untagged="true" --locked="false" --access-level="not_protected"
    deploy:
      mode: replicated
      replicas: 4
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ volumes_root }}/gitlab/gitlab-runner/config:/etc/gitlab-runner"
    networks:
      - gitlab
    depends_on:
      - gitlab
