
# https://github.com/revenz/fenrus
services:
  fenrus:
    image: revenz/fenrus
    container_name: fenrus
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /path/to/data:/app/data
    ports:
      - 3000:3000
    restart: unless-stopped