restart: unless-stopped
hostname: redis
command: |
  redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-CHANGEm3!}
dns:
  subdomain: traefik


ports:
  default: 6379

networks:
  default:
    assignIp: true
    suffix: "0.20"